"""Canonical external-dataset contracts and identity normalization."""

from .loader import (
    AVAILABLE_AT_POLICIES,
    DatasetContract,
    all_contracts,
    contract_for,
)
from .coverage import (
    COVERAGE_CONTRACT_PATH,
    COVERAGE_STATUSES,
    GOVERNANCE_TIERS,
    SNAPSHOT_SEGMENT_GRANULARITIES,
    POLICY_VERSION as COVERAGE_POLICY_VERSION,
    CollectionCoverageContract,
    all_coverage_contracts,
    coverage_contract_for,
)
from .jsda import (
    JSDA_CONTRACT_PATH,
    JSDA_CONTRACT_VERSION,
    JsdaDatasetContract,
    all_jsda_contracts,
    jsda_contract_for,
)
from .canonical import (
    REGISTRY_VERSION,
    CanonicalDatasetContract,
    all_canonical_datasets,
    canonical_dataset_for,
    experimental_datasets,
    governed_datasets,
    datasets_by_source,
    validate_downstream_consistency,
)
from .source_capability import (
    HISTORY_MODES,
    POLICY_VERSION as SOURCE_CAPABILITY_POLICY_VERSION,
    OfficialRequiredDomainSubset,
    SourceCapabilityContract,
    all_source_capability_contracts,
    apply_official_query_clamp,
    required_domain_subset_official,
    source_capability_contract_for,
)
from .permanent_defer import (
    MASTER_COVERAGE_POLICY,
    MASTER_JQ_SCOPE,
    PERMANENT_DEFER_DATASETS,
    PERMANENT_DEFER_IDS,
    SUPERSEDED_PERMANENT_DEFER_IDS,
    TIP_ONLY_POLICY,
    PermanentDeferHistoryError,
    filter_permanent_defer,
    history_densify_forbidden,
    history_reprobe_forbidden,
    is_permanent_defer,
    is_tip_only_policy,
    master_band_for_segment,
    master_coverage_policy,
    master_pre_plan_descope,
    reject_permanent_defer_for_history,
    require_history_eligible,
    tip_only_policy_for,
)

__all__ = [
    "AVAILABLE_AT_POLICIES",
    "DatasetContract",
    "all_contracts",
    "contract_for",
    "COVERAGE_CONTRACT_PATH",
    "COVERAGE_STATUSES",
    "GOVERNANCE_TIERS",
    "SNAPSHOT_SEGMENT_GRANULARITIES",
    "COVERAGE_POLICY_VERSION",
    "CollectionCoverageContract",
    "all_coverage_contracts",
    "coverage_contract_for",
    "JSDA_CONTRACT_PATH",
    "JSDA_CONTRACT_VERSION",
    "JsdaDatasetContract",
    "all_jsda_contracts",
    "jsda_contract_for",
    "REGISTRY_VERSION",
    "CanonicalDatasetContract",
    "all_canonical_datasets",
    "canonical_dataset_for",
    "experimental_datasets",
    "governed_datasets",
    "datasets_by_source",
    "validate_downstream_consistency",
    "MASTER_COVERAGE_POLICY",
    "MASTER_JQ_SCOPE",
    "PERMANENT_DEFER_DATASETS",
    "PERMANENT_DEFER_IDS",
    "SUPERSEDED_PERMANENT_DEFER_IDS",
    "TIP_ONLY_POLICY",
    "PermanentDeferHistoryError",
    "filter_permanent_defer",
    "history_densify_forbidden",
    "history_reprobe_forbidden",
    "is_permanent_defer",
    "is_tip_only_policy",
    "master_band_for_segment",
    "master_coverage_policy",
    "master_pre_plan_descope",
    "reject_permanent_defer_for_history",
    "require_history_eligible",
    "tip_only_policy_for",
    "HISTORY_MODES",
    "SOURCE_CAPABILITY_POLICY_VERSION",
    "OfficialRequiredDomainSubset",
    "SourceCapabilityContract",
    "all_source_capability_contracts",
    "apply_official_query_clamp",
    "required_domain_subset_official",
    "source_capability_contract_for",
]
