/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 846a4fa7c7148901634ce7cfd084504e)
interface __BaseEnv_Env {
	PROXY_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		PROXY_RATE_LIMITER: RateLimit;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
