/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 870247713c003e743e27f0c8d2828398)
interface __BaseEnv_Env {
	PROXY_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		PROXY_RATE_LIMITER: RateLimit;
		CF_VERSION_METADATA: WorkerVersionMetadata;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
