/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 331bcff606badad895a9545fcf5f0526)
interface __BaseEnv_Env {

}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
