"""Declarative StrategySpec schema and safe interpreter."""

from .interpreter import (
    StrategySpecStrategy,
    interpret_strategy_spec,
    resolve_feature_ref,
    resolve_strategy_features,
)
from .schema import (
    CrossSectionRankRule,
    FactorLeg,
    FactorRankRule,
    FeatureRef,
    REBALANCE_DAILY,
    REBALANCE_FIXED_HORIZON,
    STRATEGY_SPEC_VERSION,
    STRATEGY_SPEC_VERSION_V3,
    STRATEGY_SPEC_VERSION_V4,
    STRATEGY_SPEC_VERSION_V2,
    SUPPORTED_STRATEGY_SPEC_VERSIONS,
    StrategySpec,
    StrategySpecError,
    ThresholdRule,
    TopKRule,
    ValueMomentumAgreeRule,
    iter_feature_refs,
    strategy_spec_digest,
)

__all__ = [
    "CrossSectionRankRule",
    "FactorLeg",
    "FactorRankRule",
    "FeatureRef",
    "REBALANCE_DAILY",
    "REBALANCE_FIXED_HORIZON",
    "STRATEGY_SPEC_VERSION",
    "STRATEGY_SPEC_VERSION_V3",
    "STRATEGY_SPEC_VERSION_V4",
    "STRATEGY_SPEC_VERSION_V2",
    "SUPPORTED_STRATEGY_SPEC_VERSIONS",
    "StrategySpec",
    "StrategySpecError",
    "StrategySpecStrategy",
    "ThresholdRule",
    "TopKRule",
    "ValueMomentumAgreeRule",
    "interpret_strategy_spec",
    "iter_feature_refs",
    "resolve_feature_ref",
    "resolve_strategy_features",
    "strategy_spec_digest",
]
