/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env= --include-runtime=false` (hash: 5dbcf0012336a98df54f17b88b4f8437)
interface __BaseEnv_Env {
	AUTHORITY_EVIDENCE_BUCKET: R2Bucket;
	RAW_BUCKET: R2Bucket;
	STRUCTURED_BUCKET: R2Bucket;
	DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "production";
	AUTHORITY_MODE: "PENDING";
	RECEIPT_KEY_GENERATION: "1";
	RECEIPT_KEY_WRAP_KEY: string;
	RECEIPT_EVIDENCE_AUTHORITY_DO: DurableObjectNamespace<import("./src/index").ReceiptEvidenceAuthority>;
	JQUANTS_ACQUISITION: Service /* entrypoint IngestionSecretsService from quant-platform-ingestion-secrets */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ReceiptEvidenceAuthority";
	}
	interface ProductionEnv {
		AUTHORITY_EVIDENCE_BUCKET: R2Bucket;
		RAW_BUCKET: R2Bucket;
		STRUCTURED_BUCKET: R2Bucket;
		DB: D1Database;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "production";
		AUTHORITY_MODE: "PENDING";
		RECEIPT_KEY_GENERATION: "1";
		RECEIPT_KEY_WRAP_KEY: string;
		RECEIPT_EVIDENCE_AUTHORITY_DO: DurableObjectNamespace<import("./src/index").ReceiptEvidenceAuthority>;
		JQUANTS_ACQUISITION: Service /* entrypoint IngestionSecretsService from quant-platform-ingestion-secrets */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "AUTHORITY_MODE" | "RECEIPT_KEY_GENERATION" | "RECEIPT_KEY_WRAP_KEY">> {}
}
