/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env= --include-runtime=false` (hash: 543dbf698d62e5b3ccc1ed346f69a02e)
interface __BaseEnv_Env {
	AUTHORITY_EVIDENCE_BUCKET: R2Bucket;
	PRODUCT_MATERIALIZATION_BUCKET: R2Bucket;
	DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "production";
	AUTHORITY_MODE: "PENDING";
	RECEIPT_KEY_GENERATION: "1";
	RECEIPT_KEY_WRAP_KEY: string;
	RECEIPT_EVIDENCE_AUTHORITY_DO: DurableObjectNamespace<import("./src/index").ReceiptEvidenceAuthority>;
	JQUANTS_ACQUISITION: Service /* entrypoint IngestionSecretsService from quant-platform-ingestion-secrets */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ReceiptEvidenceAuthority";
	}
	interface ProductionEnv {
		AUTHORITY_EVIDENCE_BUCKET: R2Bucket;
		PRODUCT_MATERIALIZATION_BUCKET: R2Bucket;
		DB: D1Database;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "production";
		AUTHORITY_MODE: "PENDING";
		RECEIPT_KEY_GENERATION: "1";
		RECEIPT_KEY_WRAP_KEY: string;
		RECEIPT_EVIDENCE_AUTHORITY_DO: DurableObjectNamespace<import("./src/index").ReceiptEvidenceAuthority>;
		JQUANTS_ACQUISITION: Service /* entrypoint IngestionSecretsService from quant-platform-ingestion-secrets */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
