/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env= --include-runtime=false` (hash: 08039d0e127be24923494b47fe8b6146)
interface __BaseEnv_Env {
	RAW_BUCKET: R2Bucket;
	STRUCTURED_BUCKET: R2Bucket;
	AUTHORITY_EVIDENCE_BUCKET: R2Bucket;
	DB: D1Database;
	OPS_PROJECTION_DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	INGEST_CONCURRENCY: "6";
	RECEIPT_AUTHORITY_ENVIRONMENT: "production";
	RECEIPT_AUTHORITY_OPERATION_MODE: "PENDING";
	OPS_PROJECTION_ENVIRONMENT: "production";
	OPS_PROJECTION_SIGNING_KEY_ID: "ops-projection-20260826-v2";
	READY_DECLARED: "false";
	DATA_EXPORT_TOKEN: string;
	INGESTION_RUN_TOKEN: string;
	JQUANTS_API_KEY: string;
	OPS_PROJECTION_SIGNING_PKCS8_B64: string;
	READY_ED25519_PRIVATE_KEY: string;
	RECEIPT_EVIDENCE_AUTHORITY: Service /* entrypoint ReceiptAuthorityService from quant-platform-receipt-evidence-authority */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		RAW_BUCKET: R2Bucket;
		STRUCTURED_BUCKET: R2Bucket;
		AUTHORITY_EVIDENCE_BUCKET: R2Bucket;
		DB: D1Database;
		OPS_PROJECTION_DB: D1Database;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		INGEST_CONCURRENCY: "6";
		RECEIPT_AUTHORITY_ENVIRONMENT: "production";
		RECEIPT_AUTHORITY_OPERATION_MODE: "PENDING";
		OPS_PROJECTION_ENVIRONMENT: "production";
		OPS_PROJECTION_SIGNING_KEY_ID: "ops-projection-20260826-v2";
		READY_DECLARED: "false";
		DATA_EXPORT_TOKEN: string;
		INGESTION_RUN_TOKEN: string;
		JQUANTS_API_KEY: string;
		OPS_PROJECTION_SIGNING_PKCS8_B64: string;
		READY_ED25519_PRIVATE_KEY: string;
		RECEIPT_EVIDENCE_AUTHORITY: Service /* entrypoint ReceiptAuthorityService from quant-platform-receipt-evidence-authority */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
