/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env= --include-runtime=false` (hash: 9807ef392de51a9fe1eb89fb3154dc03)
interface __BaseEnv_Env {
	RAW_BUCKET: R2Bucket;
	STRUCTURED_BUCKET: R2Bucket;
	DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	INGEST_CONCURRENCY: "6";
	RECEIPT_AUTHORITY_ENVIRONMENT: "production";
	RECEIPT_AUTHORITY_OPERATION_MODE: "PENDING";
	DATA_EXPORT_TOKEN: string;
	INGESTION_RUN_TOKEN: string;
	JQUANTS_API_KEY: string;
	RECEIPT_EVIDENCE_AUTHORITY: Service /* entrypoint ReceiptAuthorityService from quant-platform-receipt-evidence-authority */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		RAW_BUCKET: R2Bucket;
		STRUCTURED_BUCKET: R2Bucket;
		DB: D1Database;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		INGEST_CONCURRENCY: "6";
		RECEIPT_AUTHORITY_ENVIRONMENT: "production";
		RECEIPT_AUTHORITY_OPERATION_MODE: "PENDING";
		DATA_EXPORT_TOKEN: string;
		INGESTION_RUN_TOKEN: string;
		JQUANTS_API_KEY: string;
		RECEIPT_EVIDENCE_AUTHORITY: Service /* entrypoint ReceiptAuthorityService from quant-platform-receipt-evidence-authority */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
