/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d184e275dd9f3abc46698b7099d47511)
interface __BaseEnv_Env {
	GITHUB_REPOSITORY: "ddnne/quant-platform";
	GITHUB_STATUS_CONTEXT: "ci-aggregate";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
