/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 32507a172612e5b7c6e9b71732caf1c3)
interface __BaseEnv_Env {
	AI: Ai;
	BUDGET_LEDGER: DurableObjectNamespace<import("./src/index").BudgetLedger>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BudgetLedger";
	}
	interface ProductionEnv {
		AI: Ai;
		BUDGET_LEDGER: DurableObjectNamespace<import("./src/index").BudgetLedger>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
