/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 004f752111b0039cdfa22782efc0439f)
interface __BaseEnv_Env {
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	GATEWAY_TOKEN: string;
	BUDGET_LEDGER: DurableObjectNamespace<import("./src/index").BudgetLedger>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BudgetLedger";
	}
	interface ProductionEnv {
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		GATEWAY_TOKEN: string;
		BUDGET_LEDGER: DurableObjectNamespace<import("./src/index").BudgetLedger>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
