/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4b8d60b2019f37466dc3c2364ba481cd)
interface __BaseEnv_Env {
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	BUDGET_LEDGER: DurableObjectNamespace<import("./src/index").BudgetLedger>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BudgetLedger";
	}
	interface ProductionEnv {
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		BUDGET_LEDGER: DurableObjectNamespace<import("./src/index").BudgetLedger>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
