/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 88fe079a732c56abf386f71c157cac21)
interface __BaseEnv_Env {
	RAW_BUCKET: R2Bucket;
	DB: D1Database;
	JSDA_QUEUE: Queue;
	USER_AGENT: "quant-platform-ingest/0.1 (+personal-research; JSDA bond stats)";
	MAX_DATA_FILES: "3";
	MAX_YEAR_PAGES: "1";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		RAW_BUCKET: R2Bucket;
		DB: D1Database;
		JSDA_QUEUE: Queue;
		USER_AGENT: "quant-platform-ingest/0.1 (+personal-research; JSDA bond stats)";
		MAX_DATA_FILES: "3";
		MAX_YEAR_PAGES: "1";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
