/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b04f67f583765c7c9f94d9956af59ea5)
interface __BaseEnv_Env {
	RAW_BUCKET: R2Bucket;
	DB: D1Database;
	JSDA_QUEUE: Queue;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	USER_AGENT: "quant-platform-ingest/0.1 (+personal-research; JSDA bond stats)";
	JSDA_DLQ_QUEUE: "quant-jsda-ingestion-dlq";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		RAW_BUCKET: R2Bucket;
		DB: D1Database;
		JSDA_QUEUE: Queue;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		USER_AGENT: "quant-platform-ingest/0.1 (+personal-research; JSDA bond stats)";
		JSDA_DLQ_QUEUE: "quant-jsda-ingestion-dlq";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
