#!/usr/bin/env python3
"""Rewrite Worker unique-logic ID/gate arrays from Python frozensets.

Python ``research.unique_logic.constants`` is SoT. Generated Worker files:
``catalog_ids.ts``, ``propose_review_tables.ts``, ``propose_allowed.ts``.
Leftover occupancy stays in daily_path.ts. Does not evaluate, promote, or
GO. Does not copy PYTHON_ONLY_EVENT_GATES onto the Worker. Run from repo root:

  PYTHONPATH=packages/product:. python scripts/sync_cf_new_thesis_ids.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

_here = Path(__file__).resolve().parent
for _d in (_here, _here.parent):
    if (_d / "_bootstrap.py").is_file():
        if str(_d) not in sys.path:
            sys.path.insert(0, str(_d))
        break
from _bootstrap import ensure_repo_root

_CATALOG_IMPORT = """import {
  CF_EVENT_LOGIC_IDS,
  CF_NEW_CS_THESIS_IDS,
  CF_NEW_EVENT_THESIS_IDS,
  CF_UNIQUE_CS_LOGIC_IDS,
  COMBO_EVENT_GATES,
} from "./catalog_ids";
export {
  CF_EVENT_LOGIC_IDS,
  CF_NEW_CS_THESIS_IDS,
  CF_NEW_EVENT_THESIS_IDS,
  CF_UNIQUE_CS_LOGIC_IDS,
} from "./catalog_ids";
"""


def _ts_array(name: str, ids: list[str]) -> str:
    inner = ",\n".join(f'  "{lid}"' for lid in ids)
    return f"export const {name} = [\n{inner},\n] as const;"


def _ts_array_spread(name: str, ids: list[str], spread: str) -> str:
    inner = ",\n".join(f'  "{lid}"' for lid in ids)
    return f"export const {name} = [\n{inner},\n  ...{spread},\n] as const;"


def _ts_set(name: str, ids: list[str], *, exported: bool = False) -> str:
    inner = ",\n".join(f'  "{lid}"' for lid in ids)
    prefix = "export const" if exported else "const"
    return f"{prefix} {name} = new Set([\n{inner},\n]);"


def _ts_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _propose_allowed_source() -> str:
    from research.cf_propose_thesis import PROPOSE_ALLOWED_DATASETS
    from research.unique_logic.constants import PROPOSE_ALLOWED_GATES
    from research.unique_logic.propose_review_tables import (
        DEFAULT_PROPOSE_DATASETS,
        PROPOSE_PROMPT_BAD,
        PROPOSE_PROMPT_PREFER_GATES,
        propose_prompt_good,
        PROPOSE_TWEAK_WORDS,
        prompt_direction_echo_x,
    )

    def arr(name: str, ids: list[str]) -> str:
        inner = ",\n".join(f"  {_ts_str(x)}" for x in ids)
        return f"export const {name} = [\n{inner},\n] as const;"

    parts = [
        "/// Generated by scripts/sync_cf_new_thesis_ids.py. Do not edit by hand.",
        "/// Python research.unique_logic.constants / propose_review_tables is SoT.",
        arr("PROPOSE_ALLOWED_GATES", sorted(PROPOSE_ALLOWED_GATES)),
        "",
        arr("PROPOSE_ALLOWED_DATASETS", sorted(PROPOSE_ALLOWED_DATASETS)),
        "",
        arr("DEFAULT_PROPOSE_DATASETS", list(DEFAULT_PROPOSE_DATASETS)),
        "",
        arr("PROPOSE_TWEAK_WORDS", list(PROPOSE_TWEAK_WORDS)),
        "",
        arr("PROMPT_DIRECTION_ECHO_X", list(prompt_direction_echo_x())),
        "",
        arr("PROPOSE_PROMPT_PREFER_GATES", list(PROPOSE_PROMPT_PREFER_GATES)),
        "",
        "export const PROPOSE_PROMPT_GOOD = "
        + json.dumps(propose_prompt_good(), ensure_ascii=True)
        + " as const;",
        "",
        f"export const PROPOSE_PROMPT_BAD = {_ts_str(PROPOSE_PROMPT_BAD)};",
        "",
    ]
    return "\n".join(parts)


def _propose_review_tables_source() -> str:
    from research.unique_logic.propose_review_tables import (
        EXTRA_TITLE_GATES,
        GATE_OCCUPANCY_LABEL,
        GATE_TITLE_CONTRA,
        OCCUPANCY_LABEL_EXCEPTIONS,
        PROPOSE_CONTRADICTORY_GATE_PAIRS,
        occupancy_extra_families,
        sparse_gate_combos_for_propose,
        TITLE_OCCUPANCY_META,
    )

    def pair_rows(rows: tuple[tuple[str, tuple[str, ...]], ...]) -> str:
        lines = []
        for gate, words in rows:
            inner = ", ".join(_ts_str(w) for w in words)
            lines.append(f"  [{_ts_str(gate)}, [{inner}]],")
        return "\n".join(lines)

    contra_pairs = []
    for pair in PROPOSE_CONTRADICTORY_GATE_PAIRS:
        inner = ", ".join(_ts_str(g) for g in sorted(pair))
        contra_pairs.append(f"  [{inner}],")
    extra_lines = [
        f"  [{_ts_str(phrase)}, {_ts_str(gate)}],"
        for phrase, gate in EXTRA_TITLE_GATES
    ]
    sparse_lines = []
    for combo in sparse_gate_combos_for_propose():
        inner = ", ".join(_ts_str(g) for g in combo)
        sparse_lines.append(f"  [{inner}],")
    except_lines = pair_rows(OCCUPANCY_LABEL_EXCEPTIONS)
    return "\n".join(
        [
            "/// Generated by scripts/sync_cf_new_thesis_ids.py. Do not edit by hand.",
            "/// Python research.unique_logic.propose_review_tables is SoT.",
            "export const GATE_TITLE_CONTRA: Array<[string, string[]]> = [",
            pair_rows(GATE_TITLE_CONTRA),
            "];",
            "",
            "export const GATE_OCCUPANCY_LABEL: Array<[string, string[]]> = [",
            pair_rows(GATE_OCCUPANCY_LABEL),
            "];",
            "",
            "export const EXTRA_TITLE_GATES: Array<[string, string]> = [",
            "\n".join(extra_lines),
            "];",
            "",
            "export const OCCUPANCY_EXTRA_TITLE: Array<[string, string[]]> = [",
            pair_rows(occupancy_extra_families()),
            "];",
            "",
            "export const PROPOSE_CONTRADICTORY_GATE_PAIRS: string[][] = [",
            "\n".join(contra_pairs),
            "];",
            "",
            "export const SPARSE_GATE_COMBOS_REVIEW: string[][] = [",
            "\n".join(sparse_lines),
            "];",
            "",
            "export const OCCUPANCY_LABEL_EXCEPTIONS: Array<[string, string[]]> = [",
            except_lines,
            "];",
            "",
            "export const TITLE_OCCUPANCY_META = [",
            ",\n".join(f"  {_ts_str(p)}" for p in TITLE_OCCUPANCY_META),
            "] as const;",
            "",
        ]
    )


def _quoted_ids(block: str) -> set[str]:
    return set(re.findall(r'"([^"]+)"', block))


def _catalog_ids_source(
    *,
    event_ids: list[str],
    event_prefix_ids: list[str],
    cs_ids: list[str],
    unique_cs_ids: list[str],
    gate_ids: list[str],
) -> str:
    parts = [
        "/// Generated by scripts/sync_cf_new_thesis_ids.py. Do not edit by hand.",
        "/// Leftover unique-22 occupancy stays in daily_path.ts.",
        _ts_array("CF_UNIQUE_CS_LOGIC_IDS", unique_cs_ids),
        _ts_array("CF_NEW_EVENT_THESIS_IDS", event_ids),
        _ts_array("CF_NEW_CS_THESIS_IDS", cs_ids),
        _ts_array_spread(
            "CF_EVENT_LOGIC_IDS", event_prefix_ids, "CF_NEW_EVENT_THESIS_IDS"
        ),
        _ts_set("COMBO_EVENT_GATES", gate_ids, exported=True),
    ]
    return "\n\n".join(parts) + "\n"


def _hoist_daily_path_ids(src: str) -> str:
    """Move generated ID arrays out of daily_path leftover occupancy."""
    out = src
    if 'from "./catalog_ids"' not in out:
        first_fn = out.find("\nfunction ")
        first_import_end = 0
        for m in re.finditer(r"^import .*;\n", out, flags=re.M):
            first_import_end = m.end()
        insert_at = first_import_end if first_import_end else first_fn
        out = out[:insert_at] + _CATALOG_IMPORT + out[insert_at:]
    for pat in (
        r"\nexport const CF_UNIQUE_CS_LOGIC_IDS = \[.*?\] as const;",
        r"\nexport const CF_NEW_EVENT_THESIS_IDS = \[.*?\] as const;",
        r"\nexport const CF_NEW_CS_THESIS_IDS = \[.*?\] as const;",
        r"\nexport const CF_EVENT_LOGIC_IDS = \[.*?\] as const;",
        r"\n(?:export )?const COMBO_EVENT_GATES = new Set\(\[.*?\]\);",
    ):
        out, n = re.subn(pat, "", out, count=1, flags=re.S)
        if n not in (0, 1):
            raise SystemExit(f"daily_path strip ambiguous: {pat!r} n={n}")
    if "export const CF_NEW_EVENT_THESIS_IDS = [" in out:
        raise SystemExit("daily_path still inlines CF_NEW_EVENT_THESIS_IDS")
    if 'from "./catalog_ids"' not in out:
        raise SystemExit("daily_path missing catalog_ids import")
    return out


def main(argv: list[str] | None = None) -> int:
    check = "--check" in list(argv if argv is not None else sys.argv[1:])
    root = ensure_repo_root()
    from research.unique_logic.constants import (
        ADAPTIVE_LOGIC_IDS,
        CF_NEW_CS_THESIS_IDS,
        CF_NEW_EVENT_THESIS_IDS,
        COMBO_EVENT_GATES,
        CS_LOGIC_IDS,
        EVENT_FILTER_LOGIC_IDS,
        EVENT_LOGIC_IDS,
        EVENT_SIDES_LOGIC_IDS,
        PROPOSE_ALLOWED_GATES,
        PYTHON_ONLY_EVENT_GATES,
    )

    py_only = set(PYTHON_ONLY_EVENT_GATES) & set(COMBO_EVENT_GATES)
    if py_only:
        raise SystemExit(
            f"COMBO_EVENT_GATES must not include PYTHON_ONLY_EVENT_GATES: "
            f"{sorted(py_only)}"
        )
    overlap = set(CS_LOGIC_IDS) & set(CF_NEW_CS_THESIS_IDS)
    if overlap:
        raise SystemExit(
            f"CS_LOGIC_IDS must stay off CF_NEW_CS_THESIS_IDS: {sorted(overlap)}"
        )
    event_prefix = (
        EVENT_LOGIC_IDS
        | EVENT_FILTER_LOGIC_IDS
        | EVENT_SIDES_LOGIC_IDS
        | ADAPTIVE_LOGIC_IDS
    )
    event_overlap = event_prefix & set(CF_NEW_EVENT_THESIS_IDS)
    if event_overlap:
        raise SystemExit(
            "event-family prefix must stay off CF_NEW_EVENT_THESIS_IDS: "
            f"{sorted(event_overlap)}"
        )

    src_dir = (
        root / "platform" / "workers" / "research-mass-eval" / "src"
    )
    ids_path = src_dir / "catalog_ids.ts"
    path = src_dir / "daily_path.ts"
    src = path.read_text(encoding="utf-8")
    ids_src = ids_path.read_text(encoding="utf-8") if ids_path.is_file() else src
    unique_m = re.search(
        r"export const CF_UNIQUE_CS_LOGIC_IDS = \[(.*?)] as const;",
        ids_src,
        flags=re.S,
    )
    if unique_m is None:
        unique_m = re.search(
            r"export const CF_UNIQUE_CS_LOGIC_IDS = \[(.*?)] as const;",
            src,
            flags=re.S,
        )
    if unique_m is None:
        raise SystemExit("CF_UNIQUE_CS_LOGIC_IDS not found")
    dropped = _quoted_ids(unique_m.group(1)) - set(CS_LOGIC_IDS)
    uncovered = dropped - set(CF_NEW_CS_THESIS_IDS)
    if uncovered:
        raise SystemExit(
            "refusing to shrink CF_UNIQUE_CS_LOGIC_IDS; dispatch would drop "
            f"{sorted(uncovered)} (not on CF_NEW_CS_THESIS_IDS)"
        )

    event_ids = sorted(CF_NEW_EVENT_THESIS_IDS)
    event_prefix_ids = sorted(event_prefix)
    cs_ids = sorted(CF_NEW_CS_THESIS_IDS)
    unique_cs_ids = sorted(CS_LOGIC_IDS)
    gate_ids = sorted(COMBO_EVENT_GATES)
    catalog_src = _catalog_ids_source(
        event_ids=event_ids,
        event_prefix_ids=event_prefix_ids,
        cs_ids=cs_ids,
        unique_cs_ids=unique_cs_ids,
        gate_ids=gate_ids,
    )
    if ids_path.is_file() and ids_path.read_text(encoding="utf-8") == catalog_src:
        print("already in sync", ids_path)
    elif check:
        raise SystemExit(f"out of sync: {ids_path}")
    else:
        ids_path.write_text(catalog_src, encoding="utf-8")
        print("rewrote", ids_path)

    src2 = _hoist_daily_path_ids(src)
    if "(CF_NEW_CS_THESIS_IDS as readonly string[]).includes(lid)" not in src2:
        raise SystemExit("dispatch/usesCrossSection must still OR CF_NEW_CS_THESIS_IDS")
    if "momentumAt(entryIdx)" not in src2 and "momentumAt(\n" not in src2:
        # leftover occupancy pin — function may be multiline
        if "function momentumAt(" not in src2:
            raise SystemExit("daily_path leftover momentumAt must stay")
    if src2 != src:
        if check:
            raise SystemExit(f"out of sync: {path}")
        path.write_text(src2, encoding="utf-8")
        print("rewrote", path)
    else:
        print("already in sync", path)

    propose_path = src_dir / "propose_thesis.ts"
    psrc = propose_path.read_text(encoding="utf-8")
    if 'from "./propose_review_tables"' not in psrc:
        raise SystemExit("propose_thesis.ts must import generated propose_review_tables")
    if 'from "./propose_allowed"' not in psrc:
        raise SystemExit("propose_thesis.ts must import generated propose_allowed")
    if "const PROPOSE_ALLOWED_GATES = [" in psrc:
        raise SystemExit("propose_thesis.ts must not inline PROPOSE_ALLOWED_GATES")
    if "const PROPOSE_ALLOWED_DATASETS = [" in psrc:
        raise SystemExit("propose_thesis.ts must not inline PROPOSE_ALLOWED_DATASETS")
    print("already in sync", propose_path)

    allowed_path = src_dir / "propose_allowed.ts"
    allowed_src = _propose_allowed_source()
    if allowed_path.is_file() and allowed_path.read_text(encoding="utf-8") == allowed_src:
        print("already in sync", allowed_path)
    elif check:
        raise SystemExit(f"out of sync: {allowed_path}")
    else:
        allowed_path.write_text(allowed_src, encoding="utf-8")
        print("rewrote", allowed_path)

    review_path = src_dir / "propose_review_tables.ts"
    review_src = _propose_review_tables_source()
    if review_path.is_file() and review_path.read_text(encoding="utf-8") == review_src:
        print("already in sync", review_path)
    elif check:
        raise SystemExit(f"out of sync: {review_path}")
    else:
        review_path.write_text(review_src, encoding="utf-8")
        print("rewrote", review_path)

    print(
        "n_event",
        len(event_ids),
        "n_event_prefix",
        len(event_prefix_ids),
        "n_cs",
        len(cs_ids),
        "n_unique_cs",
        len(unique_cs_ids),
        "n_gates",
        len(gate_ids),
        "n_propose_gates",
        len(PROPOSE_ALLOWED_GATES),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
