#!/usr/bin/env python3
"""Rewrite Worker unique-logic ID/gate arrays from Python frozensets.

Python ``research.unique_logic.constants`` is SoT. Generated Worker IDs live
in ``src/catalog_ids.ts`` (not leftover occupancy in daily_path.ts). Does
not evaluate, promote, or GO. Does not copy PYTHON_ONLY_EVENT_GATES onto
the Worker (those have no Worker gate bodies). Run from repo root:

  PYTHONPATH=packages/product:. python scripts/sync_cf_new_thesis_ids.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

_here = Path(__file__).resolve().parent
for _d in (_here, _here.parent):
    if (_d / "_bootstrap.py").is_file():
        if str(_d) not in sys.path:
            sys.path.insert(0, str(_d))
        break
from _bootstrap import ensure_repo_root

_CATALOG_IMPORT = """import {
  CF_EVENT_LOGIC_IDS,
  CF_NEW_CS_THESIS_IDS,
  CF_NEW_EVENT_THESIS_IDS,
  CF_UNIQUE_CS_LOGIC_IDS,
  COMBO_EVENT_GATES,
} from "./catalog_ids";
export {
  CF_EVENT_LOGIC_IDS,
  CF_NEW_CS_THESIS_IDS,
  CF_NEW_EVENT_THESIS_IDS,
  CF_UNIQUE_CS_LOGIC_IDS,
} from "./catalog_ids";
"""


def _ts_array(name: str, ids: list[str]) -> str:
    inner = ",\n".join(f'  "{lid}"' for lid in ids)
    return f"export const {name} = [\n{inner},\n] as const;"


def _ts_array_spread(name: str, ids: list[str], spread: str) -> str:
    inner = ",\n".join(f'  "{lid}"' for lid in ids)
    return f"export const {name} = [\n{inner},\n  ...{spread},\n] as const;"


def _ts_set(name: str, ids: list[str], *, exported: bool = False) -> str:
    inner = ",\n".join(f'  "{lid}"' for lid in ids)
    prefix = "export const" if exported else "const"
    return f"{prefix} {name} = new Set([\n{inner},\n]);"


def _quoted_ids(block: str) -> set[str]:
    return set(re.findall(r'"([^"]+)"', block))


def _catalog_ids_source(
    *,
    event_ids: list[str],
    event_prefix_ids: list[str],
    cs_ids: list[str],
    unique_cs_ids: list[str],
    gate_ids: list[str],
) -> str:
    parts = [
        "/// Generated by scripts/sync_cf_new_thesis_ids.py. Do not edit by hand.",
        "/// Leftover unique-22 occupancy stays in daily_path.ts.",
        _ts_array("CF_UNIQUE_CS_LOGIC_IDS", unique_cs_ids),
        _ts_array("CF_NEW_EVENT_THESIS_IDS", event_ids),
        _ts_array("CF_NEW_CS_THESIS_IDS", cs_ids),
        _ts_array_spread(
            "CF_EVENT_LOGIC_IDS", event_prefix_ids, "CF_NEW_EVENT_THESIS_IDS"
        ),
        _ts_set("COMBO_EVENT_GATES", gate_ids, exported=True),
    ]
    return "\n\n".join(parts) + "\n"


def _hoist_daily_path_ids(src: str) -> str:
    """Move generated ID arrays out of daily_path leftover occupancy."""
    out = src
    if 'from "./catalog_ids"' not in out:
        first_fn = out.find("\nfunction ")
        first_import_end = 0
        for m in re.finditer(r"^import .*;\n", out, flags=re.M):
            first_import_end = m.end()
        insert_at = first_import_end if first_import_end else first_fn
        out = out[:insert_at] + _CATALOG_IMPORT + out[insert_at:]
    for pat in (
        r"\nexport const CF_UNIQUE_CS_LOGIC_IDS = \[.*?\] as const;",
        r"\nexport const CF_NEW_EVENT_THESIS_IDS = \[.*?\] as const;",
        r"\nexport const CF_NEW_CS_THESIS_IDS = \[.*?\] as const;",
        r"\nexport const CF_EVENT_LOGIC_IDS = \[.*?\] as const;",
        r"\n(?:export )?const COMBO_EVENT_GATES = new Set\(\[.*?\]\);",
    ):
        out, n = re.subn(pat, "", out, count=1, flags=re.S)
        if n not in (0, 1):
            raise SystemExit(f"daily_path strip ambiguous: {pat!r} n={n}")
    if "export const CF_NEW_EVENT_THESIS_IDS = [" in out:
        raise SystemExit("daily_path still inlines CF_NEW_EVENT_THESIS_IDS")
    if 'from "./catalog_ids"' not in out:
        raise SystemExit("daily_path missing catalog_ids import")
    return out


def main(argv: list[str] | None = None) -> int:
    check = "--check" in list(argv if argv is not None else sys.argv[1:])
    root = ensure_repo_root()
    sys.path.insert(0, str(root / "packages" / "product"))
    from research.unique_logic.constants import (
        ADAPTIVE_LOGIC_IDS,
        CF_NEW_CS_THESIS_IDS,
        CF_NEW_EVENT_THESIS_IDS,
        COMBO_EVENT_GATES,
        CS_LOGIC_IDS,
        EVENT_FILTER_LOGIC_IDS,
        EVENT_LOGIC_IDS,
        EVENT_SIDES_LOGIC_IDS,
        PROPOSE_ALLOWED_GATES,
        PYTHON_ONLY_EVENT_GATES,
    )
    from research.cf_propose_thesis import PROPOSE_ALLOWED_DATASETS

    py_only = set(PYTHON_ONLY_EVENT_GATES) & set(COMBO_EVENT_GATES)
    if py_only:
        raise SystemExit(
            f"COMBO_EVENT_GATES must not include PYTHON_ONLY_EVENT_GATES: "
            f"{sorted(py_only)}"
        )
    overlap = set(CS_LOGIC_IDS) & set(CF_NEW_CS_THESIS_IDS)
    if overlap:
        raise SystemExit(
            f"CS_LOGIC_IDS must stay off CF_NEW_CS_THESIS_IDS: {sorted(overlap)}"
        )
    event_prefix = (
        EVENT_LOGIC_IDS
        | EVENT_FILTER_LOGIC_IDS
        | EVENT_SIDES_LOGIC_IDS
        | ADAPTIVE_LOGIC_IDS
    )
    event_overlap = event_prefix & set(CF_NEW_EVENT_THESIS_IDS)
    if event_overlap:
        raise SystemExit(
            "event-family prefix must stay off CF_NEW_EVENT_THESIS_IDS: "
            f"{sorted(event_overlap)}"
        )

    src_dir = (
        root / "platform" / "workers" / "research-mass-eval" / "src"
    )
    ids_path = src_dir / "catalog_ids.ts"
    path = src_dir / "daily_path.ts"
    src = path.read_text(encoding="utf-8")
    ids_src = ids_path.read_text(encoding="utf-8") if ids_path.is_file() else src
    unique_m = re.search(
        r"export const CF_UNIQUE_CS_LOGIC_IDS = \[(.*?)] as const;",
        ids_src,
        flags=re.S,
    )
    if unique_m is None:
        unique_m = re.search(
            r"export const CF_UNIQUE_CS_LOGIC_IDS = \[(.*?)] as const;",
            src,
            flags=re.S,
        )
    if unique_m is None:
        raise SystemExit("CF_UNIQUE_CS_LOGIC_IDS not found")
    dropped = _quoted_ids(unique_m.group(1)) - set(CS_LOGIC_IDS)
    uncovered = dropped - set(CF_NEW_CS_THESIS_IDS)
    if uncovered:
        raise SystemExit(
            "refusing to shrink CF_UNIQUE_CS_LOGIC_IDS; dispatch would drop "
            f"{sorted(uncovered)} (not on CF_NEW_CS_THESIS_IDS)"
        )

    event_ids = sorted(CF_NEW_EVENT_THESIS_IDS)
    event_prefix_ids = sorted(event_prefix)
    cs_ids = sorted(CF_NEW_CS_THESIS_IDS)
    unique_cs_ids = sorted(CS_LOGIC_IDS)
    gate_ids = sorted(COMBO_EVENT_GATES)
    catalog_src = _catalog_ids_source(
        event_ids=event_ids,
        event_prefix_ids=event_prefix_ids,
        cs_ids=cs_ids,
        unique_cs_ids=unique_cs_ids,
        gate_ids=gate_ids,
    )
    if ids_path.is_file() and ids_path.read_text(encoding="utf-8") == catalog_src:
        print("already in sync", ids_path)
    elif check:
        raise SystemExit(f"out of sync: {ids_path}")
    else:
        ids_path.write_text(catalog_src, encoding="utf-8")
        print("rewrote", ids_path)

    src2 = _hoist_daily_path_ids(src)
    if "(CF_NEW_CS_THESIS_IDS as readonly string[]).includes(lid)" not in src2:
        raise SystemExit("dispatch/usesCrossSection must still OR CF_NEW_CS_THESIS_IDS")
    if "momentumAt(entryIdx)" not in src2 and "momentumAt(\n" not in src2:
        # leftover occupancy pin — function may be multiline
        if "function momentumAt(" not in src2:
            raise SystemExit("daily_path leftover momentumAt must stay")
    if src2 != src:
        if check:
            raise SystemExit(f"out of sync: {path}")
        path.write_text(src2, encoding="utf-8")
        print("rewrote", path)
    else:
        print("already in sync", path)

    propose_path = src_dir / "propose_thesis.ts"
    psrc = propose_path.read_text(encoding="utf-8")
    p2, pn1 = re.subn(
        r"const PROPOSE_ALLOWED_DATASETS = \[.*?\] as const;",
        _ts_array("PROPOSE_ALLOWED_DATASETS", sorted(PROPOSE_ALLOWED_DATASETS)).replace(
            "export const ", "const "
        ),
        psrc,
        count=1,
        flags=re.S,
    )
    p2, pn2 = re.subn(
        r"const PROPOSE_ALLOWED_GATES = \[.*?\] as const;",
        _ts_array("PROPOSE_ALLOWED_GATES", sorted(PROPOSE_ALLOWED_GATES)).replace(
            "export const ", "const "
        ),
        p2,
        count=1,
        flags=re.S,
    )
    if pn1 != 1 or pn2 != 1:
        raise SystemExit(f"propose rewrite failed n_ds={pn1} n_gates={pn2}")
    if p2 != psrc:
        if check:
            raise SystemExit(f"out of sync: {propose_path}")
        propose_path.write_text(p2, encoding="utf-8")
        print("rewrote", propose_path)
    else:
        print("already in sync", propose_path)

    print(
        "n_event",
        len(event_ids),
        "n_event_prefix",
        len(event_prefix_ids),
        "n_cs",
        len(cs_ids),
        "n_unique_cs",
        len(unique_cs_ids),
        "n_gates",
        len(gate_ids),
        "n_propose_gates",
        len(PROPOSE_ALLOWED_GATES),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
