#!/usr/bin/env python3
"""Fail closed unless quant-ops-mcp governed.js is the exact generated bytes.

Implements Phase 6.2.2 §9: generated membership embeds source digest and
build/deploy must fail on drift.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

_here = Path(__file__).resolve().parent
for _d in (_here, _here.parent):
    if (_d / "_bootstrap.py").is_file():
        if str(_d) not in sys.path:
            sys.path.insert(0, str(_d))
        break
from _bootstrap import ensure_repo_root

ROOT = ensure_repo_root()

from generate_governed_js import render_governed_js  # noqa: E402

GOVERNED_JS = ROOT / "platform/workers/quant-ops-mcp/src/governed.js"


def drift_errors(path: Path = GOVERNED_JS) -> list[str]:
    """Compare one file observation to freshly rendered authoritative bytes."""
    expected = render_governed_js().encode("utf-8")
    try:
        observed = path.read_bytes()
    except FileNotFoundError:
        return [f"missing generated authority: {path}"]
    except OSError as exc:
        return [f"generated authority unavailable: {path}: {exc}"]
    if observed == expected:
        return []
    shared = min(len(observed), len(expected))
    first_difference = next(
        (offset for offset in range(shared) if observed[offset] != expected[offset]),
        shared,
    )
    observed_digest = "sha256:" + hashlib.sha256(observed).hexdigest()
    expected_digest = "sha256:" + hashlib.sha256(expected).hexdigest()
    return [
        "byte-exact generated authority drift "
        f"first_difference={first_difference} observed_bytes={len(observed)} "
        f"expected_bytes={len(expected)} observed_digest={observed_digest} "
        f"expected_digest={expected_digest}"
    ]


def main() -> int:
    errors = drift_errors(GOVERNED_JS)
    if errors:
        print("FAIL governed.js drift:", file=sys.stderr)
        for e in errors:
            print(" -", e, file=sys.stderr)
        print(
            "Regenerate: python scripts/generate_governed_js.py",
            file=sys.stderr,
        )
        return 1
    print("OK governed.js matches canonical Coverage routes and pinned digests")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
