"""Phase 7 research control plane (readiness attestation, experiment plans)."""

from research.readiness import (
    MassResearchDisabledError,
    OperatorOverrideCapability,
    OperatorOverrideService,
    ResearchReadinessService,
    VerifiedResearchReadiness,
    require_mass_research_start,
)
from research.artifacts import (
    ExperimentInsight,
    ExperimentPlan,
    FailureMode,
    FeatureEvidence,
    RegimeObservation,
    ResearchIdea,
    RejectionReason,
    StrategyEvidence,
)
from research.scheduler import (
    ExperimentScheduler,
    HypothesisClassScheduleSelection,
    ScheduledExperiment,
    select_schedule_hypothesis_classes,
)
from research.evaluation import EvaluationHarness, EvaluationProtocol, EvaluationReport
from research.single_shot_job import (
    COMPLETE_21_DATASETS,
    MASS_RESEARCH_STATUS,
    PHASE7_STATUS,
    READY_DECLARED,
    SingleShotExecution,
    SingleShotJobSpec,
    assert_mass_and_phase7_off,
    build_single_shot_job_spec,
    execute_single_shot_job,
)
from research.eval_harness import (
    APPROVED_SIGNAL_LEGS,
    MultidaySignalEval,
    assert_harness_closed,
    run_full_pipeline,
    run_multiday_signal_eval,
    run_nextday_return_eval,
)
from research.hypothesis_classes import (
    ALL_CLASS_IDS,
    CLASS_SIMPLE_DAILY_SIGN,
    DEFAULT_GENERATION_CLASS_IDS,
    HYPOTHESIS_CLASS_REGISTRY,
    HypothesisClassSpec,
    assert_simple_daily_sign_not_default_enabled,
    default_generation_class_ids,
    get_hypothesis_class,
    hypothesis_class_registry_document,
    select_generation_classes,
)
from research.idea_generator import (
    GeneratedIdeaBatch,
    default_generation_policy,
    generate_idea_payloads,
)

__all__ = [
    "ALL_CLASS_IDS",
    "APPROVED_SIGNAL_LEGS",
    "CLASS_SIMPLE_DAILY_SIGN",
    "COMPLETE_21_DATASETS",
    "DEFAULT_GENERATION_CLASS_IDS",
    "EvaluationHarness",
    "EvaluationProtocol",
    "EvaluationReport",
    "ExperimentInsight",
    "ExperimentPlan",
    "ExperimentScheduler",
    "FailureMode",
    "FeatureEvidence",
    "GeneratedIdeaBatch",
    "HYPOTHESIS_CLASS_REGISTRY",
    "HypothesisClassScheduleSelection",
    "HypothesisClassSpec",
    "MASS_RESEARCH_STATUS",
    "MassResearchDisabledError",
    "MultidaySignalEval",
    "OperatorOverrideCapability",
    "OperatorOverrideService",
    "PHASE7_STATUS",
    "READY_DECLARED",
    "RegimeObservation",
    "RejectionReason",
    "ResearchIdea",
    "ResearchReadinessService",
    "ScheduledExperiment",
    "SingleShotExecution",
    "SingleShotJobSpec",
    "StrategyEvidence",
    "VerifiedResearchReadiness",
    "assert_harness_closed",
    "assert_mass_and_phase7_off",
    "assert_simple_daily_sign_not_default_enabled",
    "build_single_shot_job_spec",
    "default_generation_class_ids",
    "default_generation_policy",
    "execute_single_shot_job",
    "generate_idea_payloads",
    "get_hypothesis_class",
    "hypothesis_class_registry_document",
    "require_mass_research_start",
    "run_full_pipeline",
    "run_multiday_signal_eval",
    "run_nextday_return_eval",
    "select_generation_classes",
    "select_schedule_hypothesis_classes",
]

