"""Compatibility re-export of fail-closed research execution flags."""
from __future__ import annotations

from features.research_freezes import (
    CONNECTED_TO_MASS,
    CONNECTED_TO_MASS_RESEARCH_LOOP,
    CONNECTED_TO_READY,
    CONTINUOUS_PAPER,
    DENSIFY,
    EDGE_CLAIMED,
    GO,
    LIVE_ORDER_PATH_ENABLED,
    LIVE_ORDERS,
    LOCAL_SOT,
    MASS_GENERATE_SIGNALS,
    MASS_RESEARCH,
    MASS_RESEARCH_ENV_ARMING_SWITCHES,
    OPERATIONAL_GO,
    ORDER_EXECUTION,
    PAPER_SCHEDULER_ARMED,
    PHASE7,
    PHASE7_ENV_ARMING_SWITCHES,
    PROMOTE_AS_MAIN,
    READY_DECLARED,
    READY_PUBLICATION,
    S1_S5_UNREJECT,
    SIGNIFICANCE_CLAIMED,
    SIMPLE_DAILY_SIGN_AS_DIVERSITY,
)
