/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env= --include-runtime=false` (hash: e868234754b95f25245bbea63671d350)
interface __BaseEnv_Env {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "disabled";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "disabled";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
