/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env= --include-runtime=false` (hash: a80406b8e0a9880d86555ccc30275af3)
interface __BaseEnv_Env {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "disabled";
	JSDA_INGESTION?: Service /* entrypoint JsdaReadinessService from quant-platform-ingestion-jsda */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "disabled";
		JSDA_INGESTION: Service /* entrypoint JsdaReadinessService from quant-platform-ingestion-jsda */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
