/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9f198968511854261752ebf4aa5a865e)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	OPS_DB: D1Database;
	ALLOWED_LOGIN: "ddnne";
	DAILY_ROW_QUOTA: "25000";
	OAUTH_AUTHORIZATION_SERVER: "https://quant-platform-ops-read-mcp.taku-haga.workers.dev";
	MCP_OBJECT: DurableObjectNamespace<import("./src/index").QuantOpsMcpAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "QuantOpsMcpAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_LOGIN" | "DAILY_ROW_QUOTA" | "OAUTH_AUTHORIZATION_SERVER">> {}
}
