/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env= --include-runtime=false` (hash: 400e267ee6a160c0e56782214f924618)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	OPS_PROJECTION_DB: D1Database;
	QUOTA_DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ALLOWED_LOGIN: "ddnne";
	DAILY_ROW_QUOTA: "25000";
	OPS_PROJECTION_ENVIRONMENT: "production";
	OPS_PROJECTION_VERIFY_KEY_ID: "ops-projection-20260826-v2";
	OAUTH_AUTHORIZATION_SERVER: "https://quant-platform-ops-read-mcp.taku-haga.workers.dev";
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	STATE_SECRET: string;
	MCP_OBJECT: DurableObjectNamespace<import("./src/index").QuantOpsMcpAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "QuantOpsMcpAgent";
	}
	interface ProductionEnv {
		OAUTH_KV: KVNamespace;
		OPS_PROJECTION_DB: D1Database;
		QUOTA_DB: D1Database;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ALLOWED_LOGIN: "ddnne";
		DAILY_ROW_QUOTA: "25000";
		OPS_PROJECTION_ENVIRONMENT: "production";
		OPS_PROJECTION_VERIFY_KEY_ID: "ops-projection-20260826-v2";
		OAUTH_AUTHORIZATION_SERVER: "https://quant-platform-ops-read-mcp.taku-haga.workers.dev";
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		STATE_SECRET: string;
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").QuantOpsMcpAgent>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_LOGIN" | "DAILY_ROW_QUOTA" | "OPS_PROJECTION_ENVIRONMENT" | "OPS_PROJECTION_VERIFY_KEY_ID" | "OAUTH_AUTHORIZATION_SERVER" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "STATE_SECRET">> {}
}
