/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6c9209e8cab565fc9a7e26bf7eb28aad)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	OPS_PROJECTION_DB: D1Database;
	QUOTA_DB: D1Database;
	ALLOWED_LOGIN: "ddnne";
	DAILY_ROW_QUOTA: "25000";
	OPS_PROJECTION_VERIFY_KEYS_JSON: "{\"schema_version\":1,\"keys\":[{\"key_id\":\"ops-projection-20260825-v1\",\"algorithm\":\"Ed25519\",\"public_key_base64\":\"1fECBb/uNUSmIn9p0AXiwBkWaAXr/FHA557sGGNpA48=\",\"status\":\"active\"}]}";
	OAUTH_AUTHORIZATION_SERVER: "https://quant-platform-ops-read-mcp.taku-haga.workers.dev";
	MCP_OBJECT: DurableObjectNamespace<import("./src/index").QuantOpsMcpAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "QuantOpsMcpAgent";
	}
	interface ProductionEnv {
		OAUTH_KV: KVNamespace;
		OPS_PROJECTION_DB: D1Database;
		QUOTA_DB: D1Database;
		ALLOWED_LOGIN: "ddnne";
		DAILY_ROW_QUOTA: "25000";
		OPS_PROJECTION_VERIFY_KEYS_JSON: "{\"schema_version\":1,\"keys\":[{\"key_id\":\"ops-projection-20260825-v1\",\"algorithm\":\"Ed25519\",\"public_key_base64\":\"1fECBb/uNUSmIn9p0AXiwBkWaAXr/FHA557sGGNpA48=\",\"status\":\"active\"}]}";
		OAUTH_AUTHORIZATION_SERVER: "https://quant-platform-ops-read-mcp.taku-haga.workers.dev";
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").QuantOpsMcpAgent>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_LOGIN" | "DAILY_ROW_QUOTA" | "OPS_PROJECTION_VERIFY_KEYS_JSON" | "OAUTH_AUTHORIZATION_SERVER">> {}
}
